Add telemetry
Azure-Samples/arm-compute-go-vm-extensions pull request #1
Opened 2017-07-14 01:16 UTC by mcardosos

PTAL
@marstr @jhendrixMSFT

2017-07-14 01:16 UTC, msftclas commented
@mcardosos,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-07-14 15:23 UTC, jhendrixMSFT commented on glide.yaml
> +  version: master
Is this because there's no tagged release with the latest changes?  If so I think we should create a tag and lock it down to that instead.

2017-07-14 17:59 UTC, mcardosos commented on glide.yaml
> +  version: master
Correct, yes

2017-07-26 19:50 UTC, marstr requested changes

2017-07-26 19:50 UTC, marstr commented on program.go
> +	sampleUA = fmt.Sprintf("sample/0005/%s", utils.GetCommit())
Honestly, I don't like the "sample/0005" tag. I think it introduces a level of indirection that we don't need. What's wrong with, `sampleUA = fmt.Sprintf("github.com/Azure-Samples/arm-compute-go-vm-extensions@%s", utils.GetCommit())`

2017-07-26 20:02 UTC, mcardosos commented on program.go
> +	sampleUA = fmt.Sprintf("sample/0005/%s", utils.GetCommit())
Too long

2018-07-13 17:53 UTC, marstr commented
Closing as stale

2018-07-13 17:53 UTC, closed without merging